name = "PlasmaFormulary"
uuid = "d26ff896-aba2-4e70-a0a6-448627456efe"
authors = ["Zijin Zhang", "Luke Adams <luke@lukeclydeadams.com>"]
version = "0.1.0"

[deps]
ChargedParticles = "e91dad46-2c06-47f2-8668-7ffa57fde2d9"
DimensionfulAngles = "2d4b8d7a-02d9-40f9-9abe-9c695b77de0d"
PermuteArgs = "9536dbe3-0ca9-4073-961c-7241c6d3471f"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulEquivalences = "da9c4bc3-91c8-4f02-8a40-6b990d2a7e0c"

[compat]
Aqua = "0.8"
ChargedParticles = "0.3.0"
DimensionfulAngles = "0.2.1"
LinearAlgebra = "1.10"
PermuteArgs = "1.2.1"
Unitful = "1.0"
UnitfulEquivalences = "0.2"
julia = "1.10"
