name: Documentation

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
      - uses: julia-actions/cache@v2
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; ChargedParticles = PackageSpec(url = "https://github.com/Beforerr/ChargedParticles.jl"); PlasmaFormulary = PackageSpec(path=pwd()); Pkg.develop([ChargedParticles, PlasmaFormulary]); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
        run: julia --project=docs/ docs/make.jl
